sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 1234

  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tRGA6rNkoy6VFkoSKAA

    access-key-secret: 3ulP5VAdLxEtypmuYx07vpkdej4QyO
    bucket-name: sky-itcast-lby

  redis:
    host: localhost
    port: 6379
    database: 10

  wechat:
    appid: wx13bbb376aa14e727
    secret: 01d112eeaa1a7804225d2cdc9a39658a
